    name: Build and Deploy URL Shortener

    on:
      push:
        branches:
          - main
      pull_request:
        branches:
          - main

    env:
      AWS_REGION: us-east-1 # Change to your desired AWS region

    jobs:
      build-and-deploy:
        runs-on: ubuntu-latest
        environment: development # Or a more specific environment if you have one configured

        steps:
          - name: Checkout code
            uses: actions/checkout@v3
            with:
              fetch-depth: 0 # Fetch all history for terraform

          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.9' # Or your desired Python version

          - name: Install Python dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r app/requirements.txt
              pip install flake8 # Install flake8 for linting

          - name: Run Flake8 Lint Check
            run: |
              flake8 app/ # Run flake8 on the app directory

          - name: Set up Terraform
            uses: hashicorp/setup-terraform@v2
            with:
              terraform_version: 1.5.0 # Specify a recent, stable Terraform version

          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v2
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ env.AWS_REGION }}

          - name: Terraform Init
            run: terraform init

          - name: Terraform Validate
            run: terraform validate

          - name: Terraform Plan
            run: terraform plan -out=tfplan

          - name: Terraform Apply
            run: terraform apply --auto-approve tfplan

          # Outputs are not directly visible in GitHub Actions Summary without additional steps
          # If you want to capture outputs, you'd add steps here to parse and display them.
    