name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python tools
        run: |
          pip install flake8 pytest

      - name: Lint and Test
        run: |
          flake8 app/
          pytest || true

      - name: Build Lambda Zips with Docker
        run: |
          docker build -t lambda-builder .
          mkdir -p build
          docker create --name temp_lambda_builder lambda-builder
          docker cp temp_lambda_builder:/build/create_link.zip ./build/create_link.zip
          docker cp temp_lambda_builder:/build/redirect.zip ./build/redirect.zip
          docker rm temp_lambda_builder

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Verify Terraform Directory
        run: |
          echo "Repo root:"
          pwd
          ls -la
          echo "terraform folder:"
          ls -la terraform
      - name: Verify aws creditinals
        run: aws sts get-caller-identity
       
      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform

      - name: Terraform Apply (main branch only)
        if: github.ref == 'refs/heads/main'
        run: terraform apply --auto-approve
        working-directory: terraform
